version: 2.1
orbs:
    ruby: circleci/ruby@1.2.0
    node: circleci/node@4.7.0
workflows:
  lint_and_test:
    jobs:
      - lint_ruby
      - lint_javascript
      - run_rspec
jobs:
  lint_ruby:
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          check-path: '--fail-level error --display-only-fail-level-offenses'
          label: Inspecting with Rubocop
      - run:
          name: Install Ruby Dependencies
          command: bundle install
  lint_javascript:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
  run_rspec:
    working_directory: ~/recruiter
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-recruiter
          RAILS_ENV: test
      - image: circleci/postgres:12.7
        environment:
          POSTGRES_DB: recruiter_test
          POSTGRES_USER: circleci-recruiter
          POSTGRES_PASSWORD: "test"
      - image: redis
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        environment:
          - cluster.name: group-project-test-cluster
          - xpack.security.enabled: false
          - transport.host: localhost
          - network.host: 127.0.0.1
          - http.port: 9200
          - discovery.type: single-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install psql
          command: sudo apt update && sudo apt install postgresql-client || true
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: 
            bundle exec rails db:create db:schema:load RAILS_ENV=test
      - run :
          name: Index candidates
          command: bundle exec rails environment elasticsearch:import:all DIR=app/models
      - run:
          name: Run Rspecs
          command:
            bundle exec rspec
      - store_test_results:
          path: test_results
