User.where({email: "admin@onmogul.com", password_digest: "$2a$12$umz4ng5pM/rW6ebixVgVBumO30rtxsUHjSX0jeiuCiY0Pk9CsfoRm", auth_token: "o3RL22e2CKM12KZabY4SSdPK", mogul_id: nil, company_id: nil, company_name: nil}).first_or_create!
Candidate.where({uid: 214027448, full_name: "Lindsey Larsen, RDH", location: "Greater Salt Lake City Area", latitude: 40.7607793, longitude: -111.8910474, bio: "<p>A highly motivated registered dental hygienist with well-developed patient skills focused on expert oral hygiene care as well as preventive management.  With ambition to reach my full potential through specialized palliative care and continued education.  A graduate from a top accredited dental hygiene program educated to diagnose and treat patients on their periodontal status.</p>", industry: "Hospital & Health Care", email: nil, linked_in_url: "https://www.linkedin.com/in/lindsey-larsen-rdh-03390740", avatar_url: "https://media-exp1.licdn.com/dms/image/C5603AQG7SMigq3T7qQ/profile-displayphoto-shrink_200_200/0?e=1602720000&v=beta&t=8CaYVsVsP7TjUWPTHJPBli7wAgoHxicZSQf_sZ1X-yg", sex_guess: "F", ethnicity_guess: "cannot_determine"},).first_or_create!
Candidate.where({uid: 214027361, full_name: "Jeff Gott", location: "Greater Chicago Area", latitude: 41.7435073, longitude: -88.0118473, bio: nil, industry: "Hospital & Health Care", email: nil, linked_in_url: "https://www.linkedin.com/in/jeff-gott-3618048", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027362, full_name: "Chefu Musonda", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "Cannot be determined", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027366, full_name: "David fair", location: "Johnson City, Tennessee Area", latitude: 36.3134397, longitude: -82.3534727, bio: nil, industry: "Telecommunications", email: nil, linked_in_url: "https://www.linkedin.com/in/david-fair-58a55a43", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "M", ethnicity_guess: "black"}).first_or_create!
Candidate.where({uid: 214027368, full_name: "Charlee Splawn", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "https://www.linkedin.com/in/charlee-splawn-1a80a276", avatar_url: nil, sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027374, full_name: "Dr. Ken Newberger", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "Cannot be determined", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027379, full_name: "Amanda Cruz Castro", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "F", ethnicity_guess: "hispanic"}).first_or_create!
Candidate.where({uid: 214027401, full_name: "Siannan Liberty", location: "Houston, Texas Area", latitude: 29.7604267, longitude: -95.3698028, bio: "<p>Job duties includes providing individual and group therapy to individuals with dual diagnosis using CBT, treatment and discharge planning and  providing psychosocial assessment. </p>", industry: "Nonprofit Organization Management", email: nil, linked_in_url: "https://www.linkedin.com/in/siannan-liberty-a0536b110", avatar_url: "https://media-exp1.licdn.com/dms/image/C5603AQEUJBcz8GUkOQ/profile-displayphoto-shrink_200_200/0?e=1606348800&v=beta&t=yu3B2FP3L0KNvw7FEnrMh_HvST4gKSHUzvO4-RL0OdU", sex_guess: "Cannot be determined", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027402, full_name: "Francine J. Aguilar", location: "Greater Chicago Area", latitude: 41.7435073, longitude: -88.0118473, bio: "<p>Experienced Project Manager with a demonstrated history of working in the wine and spirits industry. Strong arts and design professional skilled in Budgeting, Advertising, Management, Account Management, and Leadership.</p>", industry: "Marketing and Advertising", email: nil, linked_in_url: "", avatar_url: "https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAwdAAAAJDg5ZGFlOGMzLTI0YTctNGZhMC1hNWM3LTI5Yjg3YTc3YjgwMQ.jpg", sex_guess: "F", ethnicity_guess: "hispanic"}).first_or_create!
Candidate.where({uid: 214027403, full_name: "Larry Reddig", location: "Columbus, Ohio Area", latitude: 40.0154745, longitude: -82.99316069999999, bio: nil, industry: "Defense & Space", email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027408, full_name: "Rob Gomer", location: "Jersey City, New Jersey", latitude: 40.7177545, longitude: -74.0431435, bio: "<p>Professionally trained Librarian.<br>Also experience in the aviation industry.</p>", industry: "Libraries", email: nil, linked_in_url: "https://www.linkedin.com/in/rob-gomer-49505289", avatar_url: "https://media.licdn.com/dms/image/C4E03AQF3yWbMkR6KZg/profile-displayphoto-shrink_200_200/0?e=1553731200&v=beta&t=wEy3uNhO_D-1WJZjtD8MyqqOQknKN2EpmTVqKW0uhEU", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027423, full_name: "Nancy Pucillo", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027424, full_name: "Robert  w Erath", location: "West Palm Beach, Florida Area", latitude: 26.7153424, longitude: -80.0533746, bio: nil, industry: nil, email: nil, linked_in_url: "https://www.linkedin.com/in/robert-w-erath-906802a4", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027430, full_name: "Donald Nickelson", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027431, full_name: "Dennis Certa", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027434, full_name: "Jane Vogt", location: "Greater Philadelphia Area", latitude: 39.9526322, longitude: -75.1652419, bio: nil, industry: "Insurance", email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027435, full_name: "RONELL CHATMAN", location: "Homestead, Florida", latitude: 25.4687224, longitude: -80.4775569, bio: nil, industry: "Military", email: nil, linked_in_url: "https://www.linkedin.com/in/ronell-chatman-683361103", avatar_url: "https://media-exp1.licdn.com/dms/image/C5603AQH-1HvgrdceHQ/profile-displayphoto-shrink_200_200/0?e=1588809600&v=beta&t=d9HS1InU11ih2Wkz0bzdp-Lvx3sV9CRQJF9G-w9NpFE", sex_guess: "Cannot be determined", ethnicity_guess: "black"}).first_or_create!
Candidate.where({uid: 214027436, full_name: "Deb Horst", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027452, full_name: "Chase Abagnale", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027455, full_name: "Kit Cassidy", location: "Melbourne, Florida Area", latitude: 28.0836269, longitude: -80.60810889999999, bio: nil, industry: "Luxury Goods & Jewelry", email: nil, linked_in_url: "https://www.linkedin.com/in/kit-cassidy-6053221b", avatar_url: "https://media-exp1.licdn.com/dms/image/C4D03AQHeK6pATem2CQ/profile-displayphoto-shrink_200_200/0?e=1602720000&v=beta&t=Dgz_9zxOZOSgJ1j2W-rDj1Nt-hK4TNFDEjkhTltt0VQ", sex_guess: "Cannot be determined", ethnicity_guess: "hispanic"}).first_or_create!
Candidate.where({uid: 214027461, full_name: "Kimberly Falker", location: "Clearwater, Florida", latitude: 27.9658533, longitude: -82.8001026, bio: nil, industry: "Real Estate", email: nil, linked_in_url: "https://www.linkedin.com/in/kimberly-falker-a342a166", avatar_url: "https://media.licdn.com/dms/image/C5603AQFzZ570PObGjQ/profile-displayphoto-shrink_200_200/0?e=1580342400&v=beta&t=0IGKsHZjsZ27KPmEPkLJfPS_VpRn4sISiD33HUExSmc", sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027468, full_name: "Ranee Scheiman", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "https://www.linkedin.com/in/ranee-scheiman-b8553367", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027471, full_name: "JAMES DELL", location: "Martinsburg, Pennsylvania", latitude: 40.3111875, longitude: -78.3241795, bio: nil, industry: "Hospital & Health Care", email: nil, linked_in_url: "https://www.linkedin.com/in/james-dell-60987aa7", avatar_url: "https://media-exp1.licdn.com/dms/image/C4E03AQGRcAwvkE6jAg/profile-displayphoto-shrink_200_200/0?e=1612396800&v=beta&t=Z0XpzsUVU1pFExxepDWND4Nmscnx4mXdqvG4LVXoF2s", sex_guess: "M", ethnicity_guess: "black"}).first_or_create!
Candidate.where({uid: 214027473, full_name: "Carly McMahan", location: "Moyock, North Carolina", latitude: 36.524793, longitude: -76.17832469999999, bio: nil, industry: nil, email: nil, linked_in_url: "https://www.linkedin.com/in/carly-mcmahan-5089568a", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027484, full_name: "Robert M. SORENSEN", location: "Greater Denver Area", latitude: 39.7392358, longitude: -104.990251, bio: "<p>ARTISTIC BIOGRAPHY  <br><br>Robert Sorensen draws upon an international background to create works of intensely creative themes in all genres.  ART STYLE is Figurative Expressionism.<br><br>Born on the North-East Coast United States, Sorensen has spent much time abroad, living for many years near Paris in Puteaux, France. Upon his return to the U.S. Robert Sorensen settled in Colorado, where he continues to be inspired by the diverse nature, beauty and alpine skiing of the Rocky Mountain state. Painting studies at L’Académie des Beaux Arts de Chaville in France, allowed Sorensen’s natural talent to emerge and he began earning awards for his artwork, among them, prestigious honors from the French Government Art Competition, Dept. of Hauts-de-Seine, as well as Featured Artist and Editor’s Awards from various publications. <br><br>Prior to his painting career, Robert Sorensen, who holds a degree in Political Science, studied acting in New York at the Lee Strasberg Institute and toured with a professional theater group throughout the U.S.  In 2008, \"Age of 23\", a book of Sorensen’s collected literary works was published by Eloquent Books and includes 112 examples of poetic verse and free expression reflecting American and World Societies and the gamut of emotions of the human soul. <br><br>Much of Sorensen’s work is inspired by dream imagery, and slices of his own life translated onto canvas, paper or the computer screen. His art is real and vibrant, <br>unpredictable and surprising.... a daring exploration into new and unknown visionary paths and dimensions.<br><br>Full-Length Fantasy Novel Saga Series entitled:  QUANTEX QUADRUPLEX <br><br>(1) FLASHBACK 1959  &gt;&gt; 123,204 words - Final Draft<br>(2) QUANTEX GENESIS &gt;&gt;  174,657 words - Final Draft<br>(3) DARK STAR &gt;&gt; 144,005 words - First Draft Complete  <br>(4)  QUANTEX 2059 &gt;&gt; 62,000 words - Final Draft Nearly Completed  <br>(5  )ATOMIC PUNK (120 page Sci)fi ScreenPlay)  - Final Version Complete - finale episode of saga<br><br>Specialties: Bilingual in French &amp; English </p>", industry: "Fine Art", email: nil, linked_in_url: "https://www.linkedin.com/in/robert-m-sorensen-a9165412", avatar_url: "https://media-exp1.licdn.com/dms/image/C5603AQGcgXxjaq0SSQ/profile-displayphoto-shrink_200_200/0?e=1599696000&v=beta&t=fdEjZ98VbCfrNreBlqzKoaLn_M7YmBNrBx9P77_nJx0", sex_guess: "M", ethnicity_guess: "hispanic"}).first_or_create!
Candidate.where({uid: 214027489, full_name: "Linda Pt", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027491, full_name: "Eric Castanos", location: "Miami/Fort Lauderdale Area", latitude: 26.3013917, longitude: -80.6326916, bio: nil, industry: "Health, Wellness and Fitness", email: nil, linked_in_url: "https://www.linkedin.com/in/eric-castanos-97326140", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027495, full_name: "Lifang Hung", location: "Greater Chicago Area", latitude: 41.7435073, longitude: -88.0118473, bio: nil, industry: "Real Estate", email: nil, linked_in_url: "https://www.linkedin.com/in/lifang-hung-7380a818", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "Cannot be determined", ethnicity_guess: "asian"}).first_or_create!
Candidate.where({uid: 214027498, full_name: "y fu", location: "Andover, Massachusetts", latitude: 42.6583356, longitude: -71.1367953, bio: nil, industry: "Computer Software", email: nil, linked_in_url: "https://www.linkedin.com/in/y-fu-70a8a4b8", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "F", ethnicity_guess: "asian"}).first_or_create!
Candidate.where({uid: 214027502, full_name: "Donna Gillen", location: "Levittown, New York", latitude: 40.7259336, longitude: -73.51429209999999, bio: nil, industry: "Automotive", email: nil, linked_in_url: "https://www.linkedin.com/in/donna-gillen-23092354", avatar_url: nil, sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027510, full_name: "Alvetta Simpson", location: "Dallas/Fort Worth Area", latitude: 32.7078751, longitude: -96.9209135, bio: nil, industry: "Design", email: nil, linked_in_url: "https://www.linkedin.com/in/alvetta-simpson-578973bb", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "F", ethnicity_guess: "hispanic"}).first_or_create!
Candidate.where({uid: 214027511, full_name: "Rob Spragg", location: "Houston, Texas", latitude: 29.7604267, longitude: -95.3698028, bio: nil, industry: "Higher Education", email: nil, linked_in_url: "https://www.linkedin.com/in/rob-spragg-3146928b", avatar_url: "https://media-exp1.licdn.com/dms/image/C4E03AQHX26RyKeG2QQ/profile-displayphoto-shrink_200_200/0?e=1609977600&v=beta&t=f_8w_-kH-AO4tKHop8L9LHKuFZrtb3rP3nlBCmhgOPQ", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027512, full_name: "Jameca Stanfield", location: "Greater St. Louis Area", latitude: 38.8196814, longitude: -90.4502368, bio: nil, industry: "Medical Devices", email: nil, linked_in_url: "https://www.linkedin.com/in/jameca-stanfield-33746b27", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "F", ethnicity_guess: "black"}).first_or_create!
Candidate.where({uid: 214027513, full_name: "Brett Binkley", location: "Greater Atlanta Area", latitude: 33.8498184, longitude: -84.4382721, bio: nil, industry: "Telecommunications", email: nil, linked_in_url: "https://www.linkedin.com/in/brett-binkley-5604b110", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027517, full_name: "Robert Busquets", location: "Miami/Fort Lauderdale Area", latitude: 26.3013917, longitude: -80.6326916, bio: nil, industry: "Renewables & Environment", email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027518, full_name: "Pat Serzynski", location: "United States", latitude: 37.09024, longitude: -95.712891, bio: nil, industry: nil, email: nil, linked_in_url: "", avatar_url: nil, sex_guess: "Cannot be determined", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027520, full_name: "Meghan Forte", location: "Greater Pittsburgh Area", latitude: 40.3565093, longitude: -79.9192702, bio: nil, industry: "Hospital & Health Care", email: nil, linked_in_url: "https://www.linkedin.com/in/meghan-forte-b6b25660", avatar_url: "https://static-exp2.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "F", ethnicity_guess: "black"}).first_or_create!
Candidate.where({uid: 214027522, full_name: "Tanner Suchanek", location: "Clarksville, Tennessee", latitude: 36.5297706, longitude: -87.3594528, bio: nil, industry: nil, email: nil, linked_in_url: "https://www.linkedin.com/in/tanner-suchanek-9a14b86a", avatar_url: "https://media-exp1.licdn.com/dms/image/C5603AQG6u1dd1m_eRQ/profile-displayphoto-shrink_200_200/0?e=1588809600&v=beta&t=NPCKJxY3LgBn5oxbeQitHbLtVkwKj1LyvtX5MWH0dVk", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027526, full_name: "Mary Bozman", location: "Columbus, Ohio Area", latitude: 40.0154745, longitude: -82.99316069999999, bio: nil, industry: "Airlines/Aviation", email: nil, linked_in_url: "https://www.linkedin.com/in/mary-bozman-7520b735", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027533, full_name: "Elisia Triggs", location: "Cincinnati, Ohio Area", latitude: 39.1031182, longitude: -84.5120196, bio: nil, industry: "Legal Services", email: nil, linked_in_url: "https://www.linkedin.com/in/elisia-triggs-0569398", avatar_url: "https://media-exp1.licdn.com/dms/image/C4E03AQGWOujma9K4UA/profile-displayphoto-shrink_200_200/0?e=1588204800&v=beta&t=bHpVCKU9ZsQ97rtC-s9eYvB38_KTvbI29jpNKC091WU", sex_guess: "F", ethnicity_guess: "black"}).first_or_create!
Candidate.where({uid: 214027543, full_name: "Kerry Pokines", location: "Virginia Beach, Virginia", latitude: 36.8516437, longitude: -75.97921939999999, bio: nil, industry: "Hospital & Health Care", email: nil, linked_in_url: "https://www.linkedin.com/in/kerry-pokines-73822263", avatar_url: "https://static-exp1.licdn.com/sc/h/djzv59yelk5urv2ujlazfyvrk", sex_guess: "Cannot be determined", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027465, full_name: "Chris Schott", location: "Greater New York City Area", latitude: 40.7127761, longitude: -74.0059544, bio: nil, industry: "Financial Services", email: "N/A", linked_in_url: "https://www.linkedin.com/in/chris-schott-0a456a5", avatar_url: "https://static-exp1.licdn.com/sc/h/efkb5179rslll10nmhystl3wx", sex_guess: "Cannot be determined", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027360, full_name: "Cody Joyner", location: "Newport News, Virginia", latitude: 37.0870821, longitude: -76.4730122, bio: "<p>Ambitious and motivated professional with experience working independently and as a team. Skilled at building relationships with employees at all levels of the organization as well as outside vendors. Driven by a desire to increase operational efficiencies and facilitate organizational growth</p>", industry: "Banking", email: nil, linked_in_url: "https://www.linkedin.com/in/cody-joyner-25132478", avatar_url: "https://media-exp1.licdn.com/dms/image/C4E03AQHj11jY2yOK2Q/profile-displayphoto-shrink_200_200/0?e=1611792000&v=beta&t=wlyIEVXPIbeoB5gsHvEuM584zxl-uOFPsAmRV2moP3w", sex_guess: "M", ethnicity_guess: "black"}).first_or_create!
Candidate.where({uid: 214027454, full_name: "Seth Olson, P.E., CAP", location: "Bakersfield, California Area", latitude: 35.3732921, longitude: -119.0187125, bio: nil, industry: "Industrial Automation", email: "sco777@hotmail.com", linked_in_url: "https://www.linkedin.com/in/seth-olson-p-e-cap-4a282216", avatar_url: "https://media-exp1.licdn.com/dms/image/C4D03AQG42wNfKvf_TA/profile-displayphoto-shrink_200_200/0?e=1611187200&v=beta&t=tDLsSu0UgxgseF4-pXy777meQNE9MeZkH8vdRmptyJE", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027487, full_name: "Carmela Abella", location: "Port Jefferson Station, New York", latitude: 40.9253764, longitude: -73.0473284, bio: "<p>Hello and welcome to the world of design!! I've enough been told passion is the key to happiness. I couldn't agree more. My goal is to help you attain your dream home!! Want to know more? Then book a \"FREE\" 30 minute session with me. During this discovery call we can get to know one another and discuss what package that is right for you!!  <br><br></p>", industry: "Design", email: nil, linked_in_url: "https://www.linkedin.com/in/abellahomestaging", avatar_url: "https://media-exp1.licdn.com/dms/image/C4D03AQF26PtKO6hpEQ/profile-displayphoto-shrink_200_200/0?e=1612396800&v=beta&t=fU7clJ0UaTLpyNpDCl6w7HKPvCDZ6EJAxJksx_vZLpg", sex_guess: "F", ethnicity_guess: "asian"}).first_or_create!
Candidate.where({uid: 214027378, full_name: "Celia Condit", location: "Greater San Diego Area", latitude: 33.0933809, longitude: -116.6081653, bio: nil, industry: "Leisure, Travel & Tourism", email: nil, linked_in_url: "https://www.linkedin.com/in/celia-condit-5b69a65", avatar_url: "https://media-exp1.licdn.com/dms/image/C4E03AQGqZvwX-f5vkw/profile-displayphoto-shrink_200_200/0?e=1611792000&v=beta&t=0oOfcVtxN4mZuI3K53szTs6Yej48GAtugCFON2MDg38", sex_guess: "F", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027418, full_name: "Dan Bigelow", location: "Greater Salt Lake City Area", latitude: 40.7607793, longitude: -111.8910474, bio: "<p>Experienced Director Of Business Development with a demonstrated history of working in the professional training &amp; coaching industry. Skilled in Negotiation, Coaching, Sales, Value Selling, and Customer Relationship Management (CRM). Strong sales professional with a Bachelor's degree focused in Communications and Public Relations from Utah Valley University.</p>", industry: "Management Consulting", email: nil, linked_in_url: "https://www.linkedin.com/in/dan-bigelow-80a43348", avatar_url: "https://media-exp1.licdn.com/dms/image/C5603AQFYuCi8Dt7u4w/profile-displayphoto-shrink_200_200/0?e=1611792000&v=beta&t=RVMjZJozm8qwkhjs9lxIYHUDIDl-CmEkKCHm1BaMehI", sex_guess: "M", ethnicity_guess: "black"}).first_or_create!
Candidate.where({uid: 214027441, full_name: "Jhocelyn Oyola Figueroa", location: "Brooklyn, New York", latitude: 40.6781784, longitude: -73.9441579, bio: "<p>I’m Peruvian and I lived in Italy for 11 years where I started to build my career in Hospitality, Tourism and Marketing.  I’ve worked with Hotels, Resorts and Tour Operators all around the world. During that time I had the opportunity to plan, organize and execute marketing strategies in Spanish, Italian and English. Those experiences have taught me to be highly resourceful and understanding of overall client welfare.  <br><br>I’m very passionate about building productive relationships and love working in dynamically changing environments that require focused decision making and problem solving.  Now, I’m in New York to grow on those experiences.</p>", industry: "Leisure, Travel & Tourism", email: nil, linked_in_url: "https://www.linkedin.com/in/jhocelynoyolafigueroa", avatar_url: "https://media-exp1.licdn.com/dms/image/C5603AQGbyX_jYEH9EQ/profile-displayphoto-shrink_200_200/0?e=1612396800&v=beta&t=JtxoViDSnBH5XmUtiFBfNC57D0peFAVM8ldPI6G-0A4", sex_guess: "Cannot be determined", ethnicity_guess: "hispanic"}).first_or_create!
Candidate.where({uid: 214027540, full_name: "Rob Broyles", location: "Saint Petersburg, Florida", latitude: 27.7676008, longitude: -82.64029149999999, bio: "<p>20+ Years Wholesale Distribution Experience in Finance, Corporate Strategy and Operations<br><br>67+ Mergers and Acquisition Transactions closed, including financial and operational evaluations of several hundred distributors worldwide, leading due diligence efforts and full integration <br><br>$3+ billion in capital structure transactions including debt and equity issuances, term loans, revolvers, and marketing efforts<br><br>$50+ million in sale leaseback transactions of company owned real estate<br><br>Divestitures of several non core businesses, both profitable and turnaround situations<br><br>Multiple domestic and international greenfields<br><br>Carve out and stand up experience of strategic divestitures, including FloWorks International carve out from HD Supply</p>", industry: "Wholesale", email: nil, linked_in_url: "https://www.linkedin.com/in/rob-broyles-9ba9303", avatar_url: "https://media-exp1.licdn.com/dms/image/C4D03AQGnFa06xaFJ0A/profile-displayphoto-shrink_200_200/0?e=1603929600&v=beta&t=L5qXLNB3yf6Ewiif3RYvJ0sBZwGJR0SlWdpc2t8aoRs", sex_guess: "M", ethnicity_guess: "cannot_determine"}).first_or_create!
Candidate.where({uid: 214027544, full_name: "Dalton Wooten", location: "Greater Seattle Area", latitude: 47.6061031, longitude: -122.3320534, bio: "<p>My background primarily includes industrial work. When I work in a new environment I enjoy learning how to do as many things as possible which has led to a small town management and large international company trainer position. I also have experience working with customers at a small town grocery store that taught me the immediate gratification of making someone's day move smoother. I have a strong thirst for knowledge, helping others and creating a positive impact for the people who use the products/services that I have offered through my years on the workforce.</p>", industry: "Consumer Services", email: nil, linked_in_url: "https://www.linkedin.com/in/dalton-wooten-a8157b71", avatar_url: "https://media.licdn.com/dms/image/C4E03AQFNSDVxept6pg/profile-displayphoto-shrink_200_200/0?e=1576108800&v=beta&t=l-06WkUvqTD-dsLNGQTXSauZLh5Vn8IIxe7QMVpXMzU", sex_guess: "M", ethnicity_guess: "black"}).first_or_create!
# Education.where( {candidate_id: 2, uid: 1126538761, school_name: "Hampden-Sydney College", degree: "Bachelor's Degree, History", start_month: nil, start_year: 2010, end_month: nil, end_year: 2014, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 2, uid: 1126538762, school_name: "Old Dominion University", degree: "Master's Degree, Public Administration, 3.85", start_month: nil, start_year: 2014, end_month: nil, end_year: 2016, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 3, uid: 1055839859, school_name: "DePaul University", degree: nil, start_month: nil, start_year: 2002, end_month: nil, end_year: 2007, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 8, uid: 138474467, school_name: "san diego state university", degree: "bachelor of science, biology, marine science", start_month: nil, start_year: 1979, end_month: nil, end_year: 1982, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 10, uid: 138474485, school_name: "Passaic High School", degree: "Diploma", start_month: nil, start_year: 1992, end_month: nil, end_year: 1996, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 10, uid: 980607216, school_name: "Prairie View A&M University", degree: "Master of Arts (M.A.), Counseling", start_month: nil, start_year: 2011, end_month: nil, end_year: 2014, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 10, uid: 980607217, school_name: "Prairie View A&M University", degree: "bachelors, Social Work", start_month: nil, start_year: 1999, end_month: nil, end_year: 2005, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 11, uid: 331935104, school_name: "University of Illinois at Chicago", degree: "BA, English - Non Fiction", start_month: nil, start_year: 2002, end_month: nil, end_year: 2007, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 12, uid: 138474486, school_name: "Shippensburg University of Pennsylvania", degree: nil, start_month: nil, start_year: 1965, end_month: nil, end_year: 1968, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 13, uid: 566293296, school_name: nil, degree: "MLS, Library and Information Science, Graduate School", start_month: nil, start_year: 1984, end_month: nil, end_year: 1985, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 14, uid: 1140909240, school_name: "Utah Valley University", degree: "Bachelor's degree, Communications and Public Relations", start_month: nil, start_year: 2006, end_month: nil, end_year: 2009, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 16, uid: 138474497, school_name: "Hard knocks", degree: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 20, uid: 1055842012, school_name: "Anthem College-Phoenix", degree: "Associate's degree, Computer Systems Networking and Telecommunications", start_month: nil, start_year: 2001, end_month: nil, end_year: 2003, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 22, uid: 941470690, school_name: "General Assembly", degree: "Data Analytics", start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 22, uid: 1127989174, school_name: "U.E.T Scula Universitaria per il Turismo", degree: "Certificate of Professional Tourism, Tourism and Travel Services Management", start_month: nil, start_year: 2007, end_month: nil, end_year: 2010, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 22, uid: 1127989175, school_name: "CENFOTUR", degree: "Qualified Hospitality and Tourism Marketing Management, Tourism and Travel Services Marketing Operations", start_month: nil, start_year: 2015, end_month: nil, end_year: 2015, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 22, uid: 1127989176, school_name: "G.E.T Formazione Turismo", degree: "Specialization Course \"Tour Leader\", Tourism Promotion Operations", start_month: nil, start_year: 2011, end_month: nil, end_year: 2012, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 22, uid: 1127989177, school_name: "LunaMetrics", degree: "Google AdWords, Google AdWords & Google Analytics, GA 101 / GA 102 & AW 102 / AW 102", start_month: nil, start_year: 2016, end_month: nil, end_year: 2016, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 22, uid: 1127989178, school_name: "General Assembly", degree: "Facebook Advertising", start_month: nil, start_year: 2016, end_month: nil, end_year: nil, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 22, uid: 1127989179, school_name: "General Assembly", degree: "SEO Training for Startups", start_month: nil, start_year: 2017, end_month: nil, end_year: nil, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 23, uid: 933524433, school_name: "Salt Lake Community College", degree: "Applied Associate of Science, Dental Hygiene", start_month: nil, start_year: 2011, end_month: nil, end_year: 2013, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 23, uid: 933524434, school_name: "University of Utah", degree: nil, start_month: nil, start_year: 2007, end_month: nil, end_year: 2008, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 23, uid: 933524436, school_name: "Arizona State University", degree: "General Studies", start_month: nil, start_year: 2006, end_month: nil, end_year: 2007, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 25, uid: 1127835526, school_name: "Montana Tech", degree: "BS, General Engineering (Control Systems Option)", start_month: nil, start_year: 1996, end_month: nil, end_year: 2000, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 28, uid: 937837740, school_name: "Harvard University", degree: "Bachelor of Arts (BA), Biomedical/Medical Engineering", start_month: nil, start_year: 1995, end_month: nil, end_year: 1999, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 29, uid: 138474528, school_name: "Grand Canyon University", degree: "Bachelor of Science (BS), Registered Nursing/Registered Nurse", start_month: nil, start_year: 2014, end_month: nil, end_year: nil, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 30, uid: 1142113942, school_name: "Penn State University", degree: "Bachelor's degree, Dairy Science", start_month: nil, start_year: 1963, end_month: nil, end_year: 1967, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 31, uid: 1068340099, school_name: "University of Michigan", degree: nil, start_month: nil, start_year: 2014, end_month: nil, end_year: 2018, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 32, uid: 138474546, school_name: "Millburn High School", degree: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 32, uid: 933524255, school_name: "University of Hartford", degree: "BA, Pollitics & Government", start_month: nil, start_year: 1978, end_month: nil, end_year: 1982, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 32, uid: 933524256, school_name: "Infoconseil - Centre Paris - France", degree: "Certificate, 3-D Film Animation: 3-D STUDIO MAX", start_month: nil, start_year: 1999, end_month: nil, end_year: 1999, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 32, uid: 933524257, school_name: "Gobelins Ecole de Image - Paris France", degree: "certificate, Multi-media Visual Arts", start_month: nil, start_year: 1997, end_month: nil, end_year: 1997, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 32, uid: 933524258, school_name: "Lee Strasberg Theatre Institute - New York City", degree: "Film, Theatre, Television Acting Training", start_month: nil, start_year: 1984, end_month: nil, end_year: 1986, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 33, uid: 961298776, school_name: "Fashion Institute of Technology", degree: "Fashion", start_month: nil, start_year: 1979, end_month: nil, end_year: 1980, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 40, uid: 1020755274, school_name: "Western University", degree: "Master of Library & Information Science (M.L.I.S.)", start_month: nil, start_year: 1993, end_month: nil, end_year: 1995, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 40, uid: 1020755275, school_name: "University of Guelph", degree: "Bachelor of Science (BSc), Biology", start_month: nil, start_year: 1987, end_month: nil, end_year: 1992, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 42, uid: 933524451, school_name: "Georgia Institute of Technology - Georgia Tech College of Management", degree: "Bachelor of Science (BS), Management", start_month: nil, start_year: 1990, end_month: nil, end_year: 1995, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 42, uid: 933524453, school_name: "The University of Georgia", degree: "Master in Education, Sports Management", start_month: nil, start_year: 1996, end_month: nil, end_year: 1997, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 46, uid: 138474583, school_name: "New Fellowship Christian High School", degree: "High School Diploma, General Studies", start_month: nil, start_year: 2007, end_month: nil, end_year: 2010, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 46, uid: 1055842551, school_name: "Brevard Community College", degree: "General Studies (Associate Degree), Associate Degree", start_month: nil, start_year: 2013, end_month: nil, end_year: 2013, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 48, uid: 1054212405, school_name: "University of Cincinnati", degree: "B.A., English Literature, Legal Studies", start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 49, uid: 138474596, school_name: "cox high school", degree: nil, start_month: nil, start_year: 1983, end_month: nil, end_year: 1986, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 49, uid: 138474598, school_name: "Florida Southern College", degree: "5th Year Accounting, Accounting", start_month: nil, start_year: 1996, end_month: nil, end_year: 1997, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 49, uid: 933507095, school_name: "Old Dominion University", degree: "Bachelor of Science, Finance, Concentration Real Estate", start_month: nil, start_year: 1986, end_month: nil, end_year: 1991, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Education.where( {candidate_id: 51, uid: 542818314, school_name: "tarkio high", degree: nil, start_month: nil, start_year: 2007, end_month: nil, end_year: 2012, description: nil, activities_and_societies: nil, school_url: nil}).first_or_create!
# Experience.where( {candidate_id: 2, uid: 819211243, title: "Server", employment_type: nil, company_name: "Oceans & Ale", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 8, start_year: 2011, end_month: 8, end_year: 2015, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 2, uid: 975608460, title: "Student Intern", employment_type: nil, company_name: "Virginia Legal Aid Society", company_linked_in_url: nil, location: "Farmville, Virginia 23943", latitude: 37.2426032, longitude: -78.4605072, start_month: 8, start_year: 2013, end_month: 1, end_year: 2014, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 2, uid: 1842946467, title: "IT Business Analyst", employment_type: nil, company_name: "Langley Federal Credit Union", company_linked_in_url: "https://www.linkedin.com/company/langleyfcu", location: "Newport News, Virginia", latitude: 37.0870821, longitude: -76.4730122, start_month: 5, start_year: 2018, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 2, uid: 1842946469, title: "Core Conversion Specialist", employment_type: nil, company_name: "Langley Federal Credit Union", company_linked_in_url: "https://www.linkedin.com/company/langleyfcu", location: nil, latitude: nil, longitude: nil, start_month: 6, start_year: 2017, end_month: 5, end_year: 2018, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 2, uid: 1842946471, title: "Rotational Development Associate", employment_type: nil, company_name: "Langley Federal Credit Union", company_linked_in_url: "https://www.linkedin.com/company/langleyfcu", location: nil, latitude: nil, longitude: nil, start_month: 5, start_year: 2016, end_month: 6, end_year: 2017, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 2, uid: 1842946475, title: "Financial Services Representative", employment_type: nil, company_name: "Langley Federal Credit Union", company_linked_in_url: "https://www.linkedin.com/company/langleyfcu", location: "Denbigh Branch, Newport News, Virginia", latitude: 37.1456729, longitude: -76.5136476, start_month: 9, start_year: 2015, end_month: 5, end_year: 2016, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 2, uid: 1842946479, title: "Planning Intern", employment_type: nil, company_name: "City of Newport News", company_linked_in_url: "https://www.linkedin.com/company/city-of-newport-news", location: nil, latitude: nil, longitude: nil, start_month: 5, start_year: 2015, end_month: 8, end_year: 2015, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 3, uid: 306499221, title: "Director, Corporate Business Systems", employment_type: nil, company_name: "Abbott", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 5, uid: 306499235, title: "field tech", employment_type: nil, company_name: "Emzo", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 8, uid: 306499247, title: "Owner", employment_type: nil, company_name: "Searcher Sportfishing and Natural History Tours", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: 1993, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 8, uid: 306499248, title: "Education Specialist", employment_type: nil, company_name: "Zoological Society of San Diego", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 1, start_year: 1989, end_month: 1, end_year: 1995, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 8, uid: 306499249, title: "Tour Guide/Education Supervisor", employment_type: nil, company_name: "Sea World", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: 1980, end_month: nil, end_year: 1989, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 10, uid: 1491822635, title: "Therapist", employment_type: nil, company_name: "IntraCare North Hospital PHP", company_linked_in_url: nil, location: "Houston, Texas", latitude: 29.7604267, longitude: -95.3698028, start_month: 5, start_year: 2016, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 10, uid: 1491822637, title: "Mental Health Case Manager", employment_type: nil, company_name: "Texas Department of Criminal Justice - Office of the Inspector General", company_linked_in_url: "https://www.linkedin.com/company/texas-department-of-criminal-justice---office-of-the-inspector-general", location: "Houston, Texas", latitude: 29.7604267, longitude: -95.3698028, start_month: 11, start_year: 2005, end_month: 11, end_year: 2015, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 10, uid: 2486437673, title: "Case Manager", employment_type: nil, company_name: "Catholic Charities USA", company_linked_in_url: "https://www.linkedin.com/company/catholic-charities-usa", location: "Richmond, Texas", latitude: 29.5821811, longitude: -95.76078319999999, start_month: 11, start_year: 2015, end_month: 5, end_year: 2016, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 11, uid: 306499278, title: "Project Manager", employment_type: nil, company_name: "Geometry Global (formerly G2)", company_linked_in_url: "https://www.linkedin.com/company/geometry-global", location: nil, latitude: nil, longitude: nil, start_month: 1, start_year: 2013, end_month: 8, end_year: 2013, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 11, uid: 306499281, title: "Assistant Convention Director/Public Relations & Marketing Assistant", employment_type: nil, company_name: "John Robert Powers", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 11, start_year: 2006, end_month: 9, end_year: 2009, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 11, uid: 644980781, title: "Project Manager", employment_type: nil, company_name: "Schawk! Inc. / Anthem! World Wide / Anthem! Digital", company_linked_in_url: "https://www.linkedin.com/company/sgk", location: "Greater Chicago Area", latitude: 41.7435073, longitude: -88.0118473, start_month: 11, start_year: 2010, end_month: 1, end_year: 2013, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 11, uid: 740805989, title: "Operations Project Manager", employment_type: nil, company_name: "Beam Suntory", company_linked_in_url: "https://www.linkedin.com/company/beamsuntory", location: nil, latitude: nil, longitude: nil, start_month: 7, start_year: 2017, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 11, uid: 740805990, title: "Graphics Project Manager", employment_type: nil, company_name: "Beam Suntory", company_linked_in_url: "https://www.linkedin.com/company/beamsuntory", location: nil, latitude: nil, longitude: nil, start_month: 8, start_year: 2013, end_month: 7, end_year: 2017, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 11, uid: 740805991, title: "Marketing And Public Relations Manager", employment_type: nil, company_name: "John Robert Powers", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 9, start_year: 2009, end_month: 10, end_year: 2010, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 13, uid: 1455827783, title: "Librarian", employment_type: nil, company_name: "Mid-Continent Public Library", company_linked_in_url: "https://tt.linkedin.com/company/mid-continent-public-library", location: nil, latitude: nil, longitude: nil, start_month: 11, start_year: 1979, end_month: 5, end_year: 2002, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 14, uid: 2157466415, title: "Payroll and HR Consultant", employment_type: nil, company_name: "Paychex", company_linked_in_url: "https://www.linkedin.com/company/paychex", location: "Greater Salt Lake City Area", latitude: 40.7607793, longitude: -111.8910474, start_month: 12, start_year: 2010, end_month: 12, end_year: 2013, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 14, uid: 2530803225, title: "CEO", employment_type: nil, company_name: "Sandler Training Utah", company_linked_in_url: "https://www.linkedin.com/company/sandler-training-utah", location: nil, latitude: nil, longitude: nil, start_month: 5, start_year: 2020, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 14, uid: 2530803226, title: "Partner", employment_type: nil, company_name: "Sandler Training Utah", company_linked_in_url: "https://www.linkedin.com/company/sandler-training-utah", location: nil, latitude: nil, longitude: nil, start_month: 1, start_year: 2016, end_month: 4, end_year: 2020, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 14, uid: 2530803227, title: "Director of Business Development", employment_type: nil, company_name: "Sandler Training Utah", company_linked_in_url: "https://www.linkedin.com/company/sandler-training-utah", location: "Greater Salt Lake City Area", latitude: 40.7607793, longitude: -111.8910474, start_month: 7, start_year: 2013, end_month: 12, end_year: 2015, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 16, uid: 306499308, title: "5 Years", employment_type: nil, company_name: "Hidden Harbor Marine Inc", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 4, start_year: 1985, end_month: 1, end_year: 1990, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 16, uid: 306499309, title: "35 Years", employment_type: nil, company_name: "Wm. Erath & Son Inc.", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 2, start_year: 1953, end_month: 4, end_year: 1988, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 20, uid: 1781704720, title: "Military", employment_type: nil, company_name: "US Army", company_linked_in_url: "https://www.linkedin.com/company/us-army", location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2203961806, title: "Performance Media Specialist", employment_type: nil, company_name: "Havas", company_linked_in_url: "https://www.linkedin.com/company/havas", location: "Greater New York City Area", latitude: 40.7127761, longitude: -74.0059544, start_month: 8, start_year: 2018, end_month: 3, end_year: 2019, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2203961807, title: "Adwords Account Strategist", employment_type: nil, company_name: "International Musicians League", company_linked_in_url: "https://www.linkedin.com/company/international-musicians-league", location: "New York, New York", latitude: 40.7127753, longitude: -74.0059728, start_month: 11, start_year: 2016, end_month: 9, end_year: 2017, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2203961810, title: "Digital Media Coordinator", employment_type: nil, company_name: "Lima Tasty Tours EIRL", company_linked_in_url: "https://www.linkedin.com/company/lima-tasty-tours-eirl", location: "Peru", latitude: -9.189967, longitude: -75.015152, start_month: 2, start_year: 2015, end_month: 2, end_year: 2016, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2203961812, title: "Tour Leader", employment_type: nil, company_name: "Condor Travel", company_linked_in_url: "https://www.linkedin.com/company/condortravel", location: "Peru", latitude: -9.189967, longitude: -75.015152, start_month: 1, start_year: 2015, end_month: 1, end_year: 2016, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2203961814, title: "Marketing Event", employment_type: nil, company_name: "Elbow Beach Bermuda", company_linked_in_url: "https://www.linkedin.com/company/elbow-beach-bermuda", location: "Bermuda", latitude: 32.3078, longitude: -64.7505, start_month: 4, start_year: 2014, end_month: 10, end_year: 2014, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2203961815, title: "Event Specialist", employment_type: nil, company_name: "Peck", company_linked_in_url: "https://www.linkedin.com/company/peck", location: "Milan Area, Italy", latitude: 45.6068924, longitude: 9.2299404, start_month: 5, start_year: 2013, end_month: 3, end_year: 2014, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2203961817, title: "Event Services Specialist", employment_type: nil, company_name: "Four Seasons Hotels and Resorts", company_linked_in_url: "https://www.linkedin.com/company/four-seasons-hotels-and-resorts", location: "Milan Area, Italy", latitude: 45.6068924, longitude: 9.2299404, start_month: 9, start_year: 2008, end_month: 4, end_year: 2013, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2516295235, title: "Manager, Paid Search", employment_type: nil, company_name: "Mindshare", company_linked_in_url: "https://www.linkedin.com/company/mindshare", location: "New York, New York", latitude: 40.7127753, longitude: -74.0059728, start_month: 12, start_year: 2019, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2516295236, title: "Manager, Paid Search", employment_type: nil, company_name: "ForwardPMX", company_linked_in_url: "https://www.linkedin.com/company/forwardpmx", location: "New York, New York", latitude: 40.7127753, longitude: -74.0059728, start_month: 3, start_year: 2019, end_month: 12, end_year: 2019, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2516295237, title: "Performance Media Analyst", employment_type: nil, company_name: "Havas", company_linked_in_url: "https://www.linkedin.com/company/havas", location: "New York, New York", latitude: 40.7127753, longitude: -74.0059728, start_month: 11, start_year: 2017, end_month: 7, end_year: 2018, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 22, uid: 2516295238, title: "Digital Strategist - SEM - SEO -SMM", employment_type: nil, company_name: "3D Brooklyn", company_linked_in_url: "https://www.linkedin.com/company/3d-brooklyn", location: "Brooklyn, New York", latitude: 40.6781784, longitude: -73.9441579, start_month: 9, start_year: 2016, end_month: 10, end_year: 2017, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 23, uid: 1842975223, title: "Dental Hygienist", employment_type: nil, company_name: "Genesis Dental", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 3, start_year: 2014, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 23, uid: 1842975229, title: "Dental Hygienist", employment_type: nil, company_name: "Bountiful Dentistry", company_linked_in_url: nil, location: "Bountiful, Utah", latitude: 40.8893895, longitude: -111.880771, start_month: 5, start_year: 2013, end_month: 10, end_year: 2013, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 23, uid: 2224495247, title: "Business Solutions Consultant", employment_type: nil, company_name: "KSL Media", company_linked_in_url: nil, location: "Salt Lake City, Utah", latitude: 40.7607793, longitude: -111.8910474, start_month: 12, start_year: 2010, end_month: 10, end_year: 2011, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 23, uid: 2224495248, title: "Inside Sales", employment_type: nil, company_name: "Utah Jazz", company_linked_in_url: "https://www.linkedin.com/company/utah-jazz", location: "Salt Lake City, Utah", latitude: 40.7607793, longitude: -111.8910474, start_month: 4, start_year: 2008, end_month: 12, end_year: 2010, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 23, uid: 2224495249, title: "Dental Assistant", employment_type: nil, company_name: "Kent Dastrup DDS", company_linked_in_url: nil, location: "Centerville, Utah", latitude: 40.9180005, longitude: -111.8721601, start_month: 1, start_year: 2007, end_month: 4, end_year: 2008, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 25, uid: 1805590457, title: "Control Systems Engineer", employment_type: nil, company_name: "Chevron", company_linked_in_url: "https://www.linkedin.com/company/chevron", location: nil, latitude: nil, longitude: nil, start_month: 4, start_year: 2010, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 25, uid: 1805590460, title: "Control Systems Engineer", employment_type: nil, company_name: "PLCs Plus International", company_linked_in_url: "https://www.linkedin.com/company/plcs-plus-international", location: nil, latitude: nil, longitude: nil, start_month: 3, start_year: 2001, end_month: 3, end_year: 2010, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 26, uid: 1491823057, title: "Sr Retail Manager Macys Herald Square", employment_type: nil, company_name: "MAC", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: 1998, end_month: nil, end_year: 1999, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 26, uid: 1491823060, title: "Assistant Manager Cosmetics Dept", employment_type: nil, company_name: "Nordstrom Mall Of America", company_linked_in_url: nil, location: "Mall Of America Bloomington Mn", latitude: 44.8548651, longitude: -93.2422148, start_month: 8, start_year: 1998, end_month: 12, end_year: 1998, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 26, uid: 1781704577, title: "Genius", employment_type: nil, company_name: "BMW of North America, LLC", company_linked_in_url: "https://www.linkedin.com/company/bmw-of-north-america-llc", location: "Melbourne, Florida Area", latitude: 28.0836269, longitude: -80.60810889999999, start_month: 2, start_year: 2019, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 26, uid: 1781704580, title: "Retail Manager", employment_type: nil, company_name: "MAC Cosmetics", company_linked_in_url: "https://www.linkedin.com/company/mac-cosmetics", location: "Mall Of America Bloomington Mn", latitude: 44.8548651, longitude: -93.2422148, start_month: 3, start_year: 1987, end_month: 1, end_year: 1998, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 26, uid: 2271759999, title: "Account Executive", employment_type: nil, company_name: "Lafont Inc.", company_linked_in_url: nil, location: "NEW ENGLAND CT, RI, MA, NY, NH, ME, VT", latitude: 41.6032207, longitude: -73.087749, start_month: 11, start_year: 2007, end_month: 10, end_year: 2014, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 26, uid: 2467821784, title: "Sales Representative NYC", employment_type: nil, company_name: "Silhouette Optical", company_linked_in_url: nil, location: "Manhattan", latitude: 40.7830603, longitude: -73.9712488, start_month: 2, start_year: 2000, end_month: 2, end_year: 2007, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 26, uid: 2467821785, title: "Sr Retail Manager", employment_type: nil, company_name: "MAC Cosmetics", company_linked_in_url: "https://www.linkedin.com/company/mac-cosmetics", location: "Phipps Plaza,  Atlanta GA", latitude: 33.852544, longitude: -84.361986, start_month: 5, start_year: 1998, end_month: 12, end_year: 1998, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 28, uid: 1553612308, title: "Vice President", employment_type: nil, company_name: "Banc of America", company_linked_in_url: "https://www.linkedin.com/company/bank-of-america", location: nil, latitude: nil, longitude: nil, start_month: 6, start_year: 2005, end_month: 3, end_year: 2008, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 28, uid: 1842881020, title: "Associate", employment_type: nil, company_name: "Credit Suisse", company_linked_in_url: "https://www.linkedin.com/company/credit-suisse", location: nil, latitude: nil, longitude: nil, start_month: 7, start_year: 2000, end_month: 5, end_year: 2005, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 28, uid: 2056584555, title: "Managing Director", employment_type: nil, company_name: "J.P. Morgan", company_linked_in_url: "https://www.linkedin.com/company/jpmorgan", location: nil, latitude: nil, longitude: nil, start_month: 3, start_year: 2008, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 29, uid: 1203094243, title: "RN", employment_type: nil, company_name: "Banner Health", company_linked_in_url: "https://www.linkedin.com/company/banner-health", location: nil, latitude: nil, longitude: nil, start_month: 9, start_year: 2010, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 30, uid: 306499381, title: "Retired", employment_type: nil, company_name: "Village of Morrisons Cove", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 30, uid: 306499382, title: "Regional Food Safety Supervisor", employment_type: nil, company_name: "PA Dept of Agriculture", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 6, start_year: 2006, end_month: 8, end_year: 2009, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 32, uid: 2414188743, title: "Novelist - Fine Artist - Poet - Actor - World Traveler - Photographer", employment_type: nil, company_name: "Independent Contractor", company_linked_in_url: nil, location: "Greater Denver Area", latitude: 39.7392358, longitude: -104.990251, start_month: 2, start_year: 2001, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 32, uid: 2414188744, title: "English Teacher (EFL: English Foreign Language)", employment_type: nil, company_name: "ASP  Saint Cloud  FRANCE", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: 1996, end_month: nil, end_year: 2000, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 32, uid: 2414188745, title: "Marketing & Sales Consultant / French-English Translator > Corporate Expatriatition Services", employment_type: nil, company_name: "CRAIGHEAD.COM", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 9, start_year: 1999, end_month: 11, end_year: 1999, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 32, uid: 2414188746, title: "English Teacher (EFL: English Foreign Language)", employment_type: nil, company_name: "BERLITZ FRANCE", company_linked_in_url: "https://www.linkedin.com/company/berlitz-consulting", location: nil, latitude: nil, longitude: nil, start_month: 11, start_year: 1991, end_month: 5, end_year: 1996, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 32, uid: 2414188747, title: "Director of Tourism Education Division - Sales & Marketing Tourism", employment_type: nil, company_name: "INTERNATIONAL TOURS FIFTH AVENUE - New York, NY  USA", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 9, start_year: 1990, end_month: 9, end_year: 1991, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 33, uid: 2089306621, title: "Business Owner", employment_type: nil, company_name: "Abella Home Staging &  Redesign", company_linked_in_url: "https://www.linkedin.com/company/abella-home-staging-&-redesign", location: "16 Jeanne Ave Port Jefferson Station, New York", latitude: 40.9209709, longitude: -73.0637015, start_month: 2, start_year: 2009, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 33, uid: 2089306622, title: "Business Owner", employment_type: nil, company_name: "Abella Home Staging &  Redesign", company_linked_in_url: "https://www.linkedin.com/company/abella-home-staging-&-redesign", location: nil, latitude: nil, longitude: nil, start_month: 2, start_year: 2009, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 35, uid: 1302164925, title: "Owner", employment_type: nil, company_name: "Young Tigers Foundation (NON-PROFIT)", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 36, uid: 306499444, title: "Owner", employment_type: nil, company_name: "Lifang Hung", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 37, uid: 306499446, title: "Data person", employment_type: nil, company_name: "MA", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 38, uid: 306499450, title: "office/clerical", employment_type: nil, company_name: "able ford inc", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: 1990, end_month: nil, end_year: 2008, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 39, uid: 1199674746, title: "Cna", employment_type: nil, company_name: "Self -Employed", company_linked_in_url: "https://www.linkedin.com/company/self--employed_4", location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 40, uid: 2364843071, title: "Head of Computer Systems and Networking", employment_type: nil, company_name: "University of Houston", company_linked_in_url: "https://www.linkedin.com/company/university-of-houston", location: "Houston, Texas", latitude: 29.7604267, longitude: -95.3698028, start_month: 10, start_year: 1995, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 41, uid: 306499467, title: "Allograft Sales Support", employment_type: nil, company_name: "Aesculap", company_linked_in_url: "https://www.linkedin.com/company/aesculap", location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 42, uid: 1842851385, title: "Associate Director", employment_type: nil, company_name: "AT&T", company_linked_in_url: "https://www.linkedin.com/company/att", location: "Atlanta, Georgia", latitude: 33.7489954, longitude: -84.3879824, start_month: 8, start_year: 2018, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 42, uid: 2046558294, title: "Senior Contract Manager Mobility Customer Service", employment_type: nil, company_name: "AT&T", company_linked_in_url: "https://www.linkedin.com/company/att", location: "Greater Atlanta Area", latitude: 33.8498184, longitude: -84.4382721, start_month: 4, start_year: 2014, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 42, uid: 2046558295, title: "Sr Contract Manager", employment_type: nil, company_name: "AT&T", company_linked_in_url: "https://www.linkedin.com/company/att", location: "Greater Atlanta Area", latitude: 33.8498184, longitude: -84.4382721, start_month: 12, start_year: 2002, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 42, uid: 2046558297, title: "IT Sourcing Manager", employment_type: nil, company_name: "Fiserv", company_linked_in_url: "https://www.linkedin.com/company/fiserv", location: "Norcross, GA", latitude: 33.9411081, longitude: -84.2137443, start_month: 8, start_year: 2007, end_month: 4, end_year: 2008, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 42, uid: 2046558298, title: "Senior Contract Manager", employment_type: nil, company_name: "Cingular Wireless", company_linked_in_url: nil, location: "Greater Atlanta Area", latitude: 33.8498184, longitude: -84.4382721, start_month: 4, start_year: 2002, end_month: 8, end_year: 2007, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 46, uid: 306499483, title: "N/A", employment_type: nil, company_name: "N/A", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 47, uid: 1183877043, title: "Flight Attendant", employment_type: nil, company_name: "Republic Airlines", company_linked_in_url: "https://www.linkedin.com/company/republic-airlines", location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 48, uid: 306499496, title: "Owner", employment_type: nil, company_name: "The One Group LLC", company_linked_in_url: nil, location: nil, latitude: nil, longitude: nil, start_month: 8, start_year: 2009, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 49, uid: 1842898206, title: "Chief Financial Officer, PVF Group of HD Supply", employment_type: nil, company_name: "HD Supply", company_linked_in_url: "https://www.linkedin.com/company/hd-supply", location: "Houston, Texas Area", latitude: 29.7604267, longitude: -95.3698028, start_month: nil, start_year: 2004, end_month: nil, end_year: 2012, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 49, uid: 1842898208, title: "Assistant Treasurer, Capital Markets, Hughes Supply", employment_type: nil, company_name: "Hughes Supply", company_linked_in_url: "https://www.linkedin.com/company/hughes-supply", location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: 2001, end_month: 9, end_year: 2003, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 49, uid: 1842898211, title: "Director Mergers and Acquisitions", employment_type: nil, company_name: "Hughes Supply", company_linked_in_url: "https://www.linkedin.com/company/hughes-supply", location: nil, latitude: nil, longitude: nil, start_month: 1, start_year: 1998, end_month: nil, end_year: 2001, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 49, uid: 2167583956, title: "General Partner", employment_type: nil, company_name: "Underoaks Capital", company_linked_in_url: nil, location: "Tampa/St. Petersburg, Florida Area", latitude: 28.274347, longitude: -82.38857829999999, start_month: 5, start_year: 2018, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 49, uid: 2254450718, title: "Executive Vice President. Strategy & Corporate Development", employment_type: nil, company_name: "FloWorks International", company_linked_in_url: "https://www.linkedin.com/company/floworks-international", location: "Houston, Texas Area", latitude: 29.7604267, longitude: -95.3698028, start_month: nil, start_year: 2012, end_month: 11, end_year: 2018, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 49, uid: 2254450719, title: "Executive Vice President Corporate Finance", employment_type: nil, company_name: "FloWorks International", company_linked_in_url: "https://www.linkedin.com/company/floworks-international", location: "Houston, Texas Area", latitude: 29.7604267, longitude: -95.3698028, start_month: 11, start_year: 2017, end_month: 4, end_year: 2018, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 50, uid: 306499507, title: "CHAPLAIN", employment_type: nil, company_name: "Bon Secours Health System", company_linked_in_url: "https://www.linkedin.com/company/bon-secours-health-system", location: nil, latitude: nil, longitude: nil, start_month: nil, start_year: nil, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 51, uid: 1380280292, title: "Assembler", employment_type: nil, company_name: "sound assembly services", company_linked_in_url: nil, location: "Tacoma, Washington", latitude: 47.2528768, longitude: -122.4442906, start_month: 5, start_year: 2017, end_month: nil, end_year: nil, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 51, uid: 1380280293, title: "Trainer", employment_type: nil, company_name: "Focus Workforce Management", company_linked_in_url: "https://www.linkedin.com/company/focus-workforces", location: "Maryville, Missouri", latitude: 40.3461017, longitude: -94.8724706, start_month: 10, start_year: 2015, end_month: 3, end_year: 2017, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 51, uid: 1380280294, title: "Floor Manager", employment_type: nil, company_name: "barrington manufacturing inc llc", company_linked_in_url: nil, location: "El Dorado Springs, Missouri", latitude: 37.87697989999999, longitude: -94.0213303, start_month: 6, start_year: 2013, end_month: 8, end_year: 2015, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 51, uid: 1380280295, title: "Assistant", employment_type: nil, company_name: "gary wooten", company_linked_in_url: nil, location: "El Dorado Springs, Missouri", latitude: 37.87697989999999, longitude: -94.0213303, start_month: 7, start_year: 2012, end_month: 9, end_year: 2012, description: nil, media_urls: [], company_id: nil}).first_or_create!
# Experience.where( {candidate_id: 51, uid: 1380280296, title: "Stocker", employment_type: nil, company_name: "Hy-vee", company_linked_in_url: nil, location: "Tarkio, Missouri", latitude: 40.4402763, longitude: -95.37775859999999, start_month: nil, start_year: 2010, end_month: nil, end_year: 2011, description: nil, media_urls: [], company_id: nil}).first_or_create!
Company.where({ uid: Faker::Number.number(digits: 10), name: 'Nike', employees_count: 10 }).first_or_create!
Pipeline.where({ name: Faker::Coffee.blend_name, user_id: User.first.id }).first_or_create!
SavedCandidate.where({ pipeline_id: Pipeline.last.id, candidate_id: Candidate.first.id }).first_or_create!
